#ifndef __REG_EM_BLE_RX_ISO_DESC_H_
#define __REG_EM_BLE_RX_ISO_DESC_H_

#define REG_EM_BLE_RX_ISO_DESC_SIZE 12

#define REG_EM_BLE_RX_ISO_DESC_BASE_ADDR 0x00910000


#endif // __REG_EM_BLE_RX_ISO_DESC_H_

