#ifndef __REG_EM_BLE_RX_AUDIO_BUF_H_
#define __REG_EM_BLE_RX_AUDIO_BUF_H_

#define REG_EM_BLE_RX_AUDIO_BUF_SIZE 64

#define REG_EM_BLE_RX_AUDIO_BUF_BASE_ADDR 0x00910000


#endif // __REG_EM_BLE_RX_AUDIO_BUF_H_

