#ifndef __REG_EM_BLE_RX_ISO_BUF_H_
#define __REG_EM_BLE_RX_ISO_BUF_H_

#define REG_EM_BLE_RX_ISO_BUF_SIZE 68

#define REG_EM_BLE_RX_ISO_BUF_BASE_ADDR 0x00910000


#endif // __REG_EM_BLE_RX_ISO_BUF_H_

