#ifndef _BK3633_REGLIST_H_
#define _BK3633_REGLIST_H_

//************************************************************//
//XVR
//************************************************************//
#define BASEADDR_XVR                                            (0x0080B400)

#define BLE_XVR_REG00											(BASEADDR_XVR + 0x00 * 4)
#define BLE_XVR_REG01											(BASEADDR_XVR + 0x01 * 4)
#define BLE_XVR_REG02											(BASEADDR_XVR + 0x02 * 4)
#define BLE_XVR_REG03											(BASEADDR_XVR + 0x03 * 4)
#define BLE_XVR_REG04											(BASEADDR_XVR + 0x04 * 4)
#define BLE_XVR_REG05											(BASEADDR_XVR + 0x05 * 4)
#define BLE_XVR_REG06											(BASEADDR_XVR + 0x06 * 4)
#define BLE_XVR_REG07											(BASEADDR_XVR + 0x07 * 4)
#define BLE_XVR_REG08											(BASEADDR_XVR + 0x08 * 4)
#define BLE_XVR_REG09											(BASEADDR_XVR + 0x09 * 4)
#define BLE_XVR_REG0A											(BASEADDR_XVR + 0x0A * 4)
#define BLE_XVR_REG0B											(BASEADDR_XVR + 0x0B * 4)
#define BLE_XVR_REG0C											(BASEADDR_XVR + 0x0C * 4)
#define BLE_XVR_REG0D											(BASEADDR_XVR + 0x0D * 4)
#define BLE_XVR_REG0E											(BASEADDR_XVR + 0x0E * 4)
#define BLE_XVR_REG0F											(BASEADDR_XVR + 0x0F * 4)
#define BLE_XVR_REG10											(BASEADDR_XVR + 0x10 * 4)
#define BLE_XVR_REG11											(BASEADDR_XVR + 0x11 * 4)
#define BLE_XVR_REG12											(BASEADDR_XVR + 0x12 * 4)
#define BLE_XVR_REG13											(BASEADDR_XVR + 0x13 * 4)
#define BLE_XVR_REG14											(BASEADDR_XVR + 0x14 * 4)
#define BLE_XVR_REG15											(BASEADDR_XVR + 0x15 * 4)
#define BLE_XVR_REG16											(BASEADDR_XVR + 0x16 * 4)
#define BLE_XVR_REG17											(BASEADDR_XVR + 0x17 * 4)
#define BLE_XVR_REG18											(BASEADDR_XVR + 0x18 * 4)
#define BLE_XVR_REG19											(BASEADDR_XVR + 0x19 * 4)
#define BLE_XVR_REG1A											(BASEADDR_XVR + 0x1A * 4)
#define BLE_XVR_REG1B											(BASEADDR_XVR + 0x1B * 4)
#define BLE_XVR_REG1C											(BASEADDR_XVR + 0x1C * 4)
#define BLE_XVR_REG1D											(BASEADDR_XVR + 0x1D * 4)
#define BLE_XVR_REG1E											(BASEADDR_XVR + 0x1E * 4)
#define BLE_XVR_REG1F											(BASEADDR_XVR + 0x1F * 4)
#define BLE_XVR_REG20											(BASEADDR_XVR + 0x20 * 4)
#define BLE_XVR_REG21											(BASEADDR_XVR + 0x21 * 4)
#define BLE_XVR_REG22											(BASEADDR_XVR + 0x22 * 4)
#define BLE_XVR_REG23											(BASEADDR_XVR + 0x23 * 4)
#define BLE_XVR_REG24											(BASEADDR_XVR + 0x24 * 4)
#define BLE_XVR_REG25											(BASEADDR_XVR + 0x25 * 4)
#define BLE_XVR_REG26											(BASEADDR_XVR + 0x26 * 4)
#define BLE_XVR_REG27											(BASEADDR_XVR + 0x27 * 4)
#define BLE_XVR_REG28											(BASEADDR_XVR + 0x28 * 4)
#define BLE_XVR_REG29											(BASEADDR_XVR + 0x29 * 4)
#define BLE_XVR_REG2A											(BASEADDR_XVR + 0x2A * 4)
#define BLE_XVR_REG2B											(BASEADDR_XVR + 0x2B * 4)
#define BLE_XVR_REG2C											(BASEADDR_XVR + 0x2C * 4)
#define BLE_XVR_REG2D											(BASEADDR_XVR + 0x2D * 4)
#define BLE_XVR_REG2E											(BASEADDR_XVR + 0x2E * 4)
#define BLE_XVR_REG2F											(BASEADDR_XVR + 0x2F * 4)
#define BLE_XVR_REG30											(BASEADDR_XVR + 0x30 * 4)
#define BLE_XVR_REG31											(BASEADDR_XVR + 0x31 * 4)
#define BLE_XVR_REG32											(BASEADDR_XVR + 0x32 * 4)
#define BLE_XVR_REG33											(BASEADDR_XVR + 0x33 * 4)
#define BLE_XVR_REG34											(BASEADDR_XVR + 0x34 * 4)
#define BLE_XVR_REG35											(BASEADDR_XVR + 0x35 * 4)
#define BLE_XVR_REG36											(BASEADDR_XVR + 0x36 * 4)
#define BLE_XVR_REG37											(BASEADDR_XVR + 0x37 * 4)
#define BLE_XVR_REG38											(BASEADDR_XVR + 0x38 * 4)
#define BLE_XVR_REG39											(BASEADDR_XVR + 0x39 * 4)
#define BLE_XVR_REG3A											(BASEADDR_XVR + 0x3A * 4)
#define BLE_XVR_REG3B											(BASEADDR_XVR + 0x3B * 4)
#define BLE_XVR_REG3C											(BASEADDR_XVR + 0x3C * 4)
#define BLE_XVR_REG3D											(BASEADDR_XVR + 0x3D * 4)
#define BLE_XVR_REG3E											(BASEADDR_XVR + 0x3E * 4)
#define BLE_XVR_REG3F											(BASEADDR_XVR + 0x3F * 4)
#define BLE_XVR_REG40											(BASEADDR_XVR + 0x40 * 4)
#define BLE_XVR_REG41											(BASEADDR_XVR + 0x41 * 4)
#define BLE_XVR_REG42											(BASEADDR_XVR + 0x42 * 4)
#define BLE_XVR_REG43											(BASEADDR_XVR + 0x43 * 4)
#define BLE_XVR_REG44											(BASEADDR_XVR + 0x44 * 4)
#define BLE_XVR_REG45											(BASEADDR_XVR + 0x45 * 4)
#define BLE_XVR_REG46											(BASEADDR_XVR + 0x46 * 4)
#define BLE_XVR_REG47											(BASEADDR_XVR + 0x47 * 4)
#define BLE_XVR_REG48											(BASEADDR_XVR + 0x48 * 4)
#define BLE_XVR_REG49											(BASEADDR_XVR + 0x49 * 4)
#define BLE_XVR_REG4A											(BASEADDR_XVR + 0x4A * 4)
#define BLE_XVR_REG4B											(BASEADDR_XVR + 0x4B * 4)
#define BLE_XVR_REG4C											(BASEADDR_XVR + 0x4C * 4)
#define BLE_XVR_REG4D											(BASEADDR_XVR + 0x4D * 4)
#define BLE_XVR_REG4E											(BASEADDR_XVR + 0x4E * 4)
#define BLE_XVR_REG4F											(BASEADDR_XVR + 0x4F * 4)

#define BLE_XVR_CHAN_MASK										(0x7F)
#define BLE_XVR_CHAN_POST										(0)
#define BLE_XVR_AUTO_CHAN_MASK									(0xF)
#define BLE_XVR_AUTO_CHAN_POST									(17)

#define REG_READ(addr)          *((volatile uint32_t *)(addr))
#define REG_WRITE(addr, _data)  (*((volatile uint32_t *)(addr)) = (_data))

#endif
